version: "3.8"
services:
  cassandra:
      image: cassandra:4.1.4
      container_name: cassandra
      ports:
        - 6999:6999
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
      restart: always
      environment:
        - CASSANDRA_BROADCAST_ADDRESS=host.docker.internal
        - CASSANDRA_SEEDS=host.docker.internal

      volumes:
        - ./out/cassandra_data:/var/lib/cassandra
      healthcheck:
        test: ["CMD","cqlsh","-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10